---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - '3500:3500'
    environment:
      ZOOKEEPER_CLIENT_PORT: 3500
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    depends_on:
      - zookeeper
    ports:
      - '3501:3501'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:3500'
      KAFKA_ADVERTISED_LISTENERS: 'EXTERNAL://localhost:3501,PLAINTEXT://broker:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_LISTENERS: 'EXTERNAL://0.0.0.0:3501,PLAINTEXT://0.0.0.0:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 100000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 100000000

  schema_registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema_registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - '3502:3502'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:3502'
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:3500'
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker:9092'

  kafka_rest:
    image: confluentinc/cp-kafka-rest:latest
    hostname: kafka_rest
    depends_on:
      - zookeeper
      - schema_registry
      - broker
    ports:
      - '8082:8082'
    environment:
      KAFKA_REST_HOST_NAME: kafka_rest
      KAFKA_REST_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker:9092'
      KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:3500'
      KAFKA_REST_LISTENERS: 'http://0.0.0.0:8082'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema_registry:3502'
      KAFKA_CONSUMER_REQUEST_TIMEOUT_MS: 30000
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,DELETE,OPTIONS'
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: '*'

  kafka_topics_ui:
    image: landoop/kafka-topics-ui:latest
    hostname: kafka_topics_ui
    depends_on:
      - kafka_rest
    ports:
      - '3600:8000'
    environment:
      KAFKA_REST_PROXY_URL: 'http://kafka_rest:8082'
      PROXY: 'true'

  kafka_schema_registry_ui:
    image: landoop/schema-registry-ui:latest
    hostname: kafka_schema_registry_ui
    depends_on:
      - schema_registry
    ports:
      - '3601:8000'
    environment:
      SCHEMAREGISTRY_URL: 'http://schema_registry:3502'
      PROXY: 'true'

  # postgres:
  #   image: postgres:9.6
  #   hostname: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: TRIAL_ADMIN
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   restart: unless-stopped

  # admintool:
  #   image: drivereu/test-bed-admin:latest
  #   depends_on:
  #     - postgres
  #     - broker
  #     - schema_registry
  #   ports:
  #     - '8090:8090'
  #   volumes:
  #     - ./admintool-config/gateways.json:/opt/application/config/gateways.json
  #     - ./admintool-config/solutions.json:/opt/application/config/solutions.json
  #     - ./admintool-config/topics.json:/opt/application/config/topics.json
  #     - ./admintool-config/standards.json:/opt/application/config/standards.json
  #   environment:
  #     KAFKA_BROKER_URL: broker:9092
  #     SCHEMA_REGISTRY_URL: http://schema_registry:3502
  #     zookeeper_host: zookeeper
  #     zookeeper_port: 3500
  #     schema_registry_url: http://schema_registry:3502
  #     testbed_secure_mode: 'DEVELOP'
  #     testbed_init_auto: 'false'
  #     management_ca_cert_path: http://localhost:9090
  #     cert_handler_url: https://localhost:8443
  #     cert_pem_handler_url: https://localhost:8443
  #     security_rest_path_group: https://localhost:9443
  #     security_rest_path_topic: https://localhost:9443

  # afteractionreview:
  #   image: drivereu/after-action-review:latest
  #   depends_on:
  #     - postgres
  #     - broker
  #     - schema_registry
  #   ports:
  #     - '8095:8095'
  #   environment:
  #     KAFKA_BROKER_URL: broker:9092
  #     SCHEMA_REGISTRY_URL: http://schema_registry:3502
  #     zookeeper_host: zookeeper
  #     zookeeper_port: 3500
  #     schema_registry_url: http://schema_registry:3502

  # pgadmin:
  #   image: fenglc/pgadmin4
  #   depends_on:
  #     - postgres
  #   ports:
  #     - '5050:5050'
  #   restart: unless-stopped

  time_service:
    image: drivereu/test-bed-time-service:latest
    depends_on:
      - broker
      - schema_registry
    ports:
      - '8100:8100'
    environment:
      KAFKA_BROKER_URL: broker:9092
      SCHEMA_REGISTRY_URL: http://schema_registry:3502
      AUTO_REGISTER_SCHEMAS: 'false'
      INTERVAL: 1000

  # large_file_service:
  #   image: drivereu/large-file-service:latest
  #   ports:
  #     - '9090:9090'
  #   environment:
  #     HOST: localhost
  #     PORT: 9090

  # lcms_connector:
  #   image: drivereu/lcms-connector:1.0.5
  #   hostname: lcms_connector
  #   environment:
  #     KAFKA_BROKER_URL: broker:9092
  #     SCHEMA_REGISTRY_URL: http://schema_registry:3502
  #     LCMS_CONNECTOR_SERVER_PORT: 5000
  #     LCMS_CONNECTOR_SSL_MODE: 'false'
  #     LCMS_CONNECTOR_SERVER_MODE: 'true'
  #     LCMS_CONNECTOR_KAFKA_MODE: 'true'
  #     LCMS_CONNECTOR_DEBUG_MODE: 'true'
  #     LCMS_CONNECTOR_EXCERCISE: 'DRIVEREU'
  #     LCMS_CONNECTOR_USERNAME: '${LCMS_CONNECTOR_USERNAME}'
  #     LCMS_CONNECTOR_PASSWORD: '${LCMS_CONNECTOR_PASSWORD}'
  #   ports:
  #     - 8500:5000
  #   depends_on:
  #     - broker
  #     - schema_registry

  # trial_management_tool:
  #   image: drivereu/trial-management-tool:latest
  #   depends_on:
  #     - broker
  #     - schema_registry
  #   ports:
  #     - '3210:3210'
  #   environment:
  #     CLIENT_ID: TB-TrialMgmt
  #     KAFKA_HOST: broker:9092
  #     SCHEMA_REGISTRY: http://schema_registry:3502
  #     TRIAL_MANAGER_SERVER_PORT: 3210
  #     PRODUCE: system_request_change_of_trial_stage,system_tm_phase_message,system_tm_role_player,system_tm_session_mgmt,standard_cap,simulation_request_startinject,sumo_AffectedArea,simulation_request_unittransport,sumo_SumoConfiguration,simulation_entity_post
  #     SSL: 'false'
  #     SSL_PFX: certs/TB-TrialMgmt.p12
  #     SSL_PASSPHRASE: changeit
  #     SSL_CA: certs/test-ca.pem
  #   volumes:
  #     - trial-data:/app/trials

  silent-producer:
    image: drivereu/silent-producer:0.0.1
    depends_on:
      - broker
      - schema_registry
    environment:
      KAFKA_HOST: broker:9092
      SCHEMA_REGISTRY: http://schema_registry:3502
      PRODUCE_TOPICS: chemical_hazard,standard_cap,standard_geojson,system_timing,system_topic_access_invite
    restart: on-failure
    volumes:
      - ./schemas:/src/schemas

# volumes:
  # postgres-data:
  # trial-data:
  # maildata:
  # mailstate:
  # mailconfig:
