import { Form, padLeft } from 'mithril-ui-form';
import {
  CbrnOutput,
  IChemicalHazard,
  IControlParameters,
  IScenarioDefinition,
  PasquillClass,
} from '../../../shared/src';

/** Additional properties for internal usage */
export interface IChemicalHazardExt extends IChemicalHazard {
  extended?: {
    type_of_release?: string;
  };
}

const convertTime = /[\d-]* (\d{2}):(\d{2})/gm;

const transform = (dir: 'from' | 'to', v: string | Date) => {
  if (dir === 'from') {
    const m = convertTime.exec(v as string);
    if (m) {
      const d = new Date();
      d.setHours(+m[1], +m[2]);
      return d;
    }
    return new Date();
  } else {
    const d = v as Date;
    return `${padLeft(d.getDate())}-${padLeft(
      d.getMonth() + 1
    )}-${d.getFullYear()} ${padLeft(d.getHours())}:${padLeft(d.getMinutes())}`;
  }
};

export const formGenerator = (source: Partial<IChemicalHazardExt>): Form => {
  if (!source.control_parameters) {
    source.control_parameters = {
      max_dist: 1000,
      z: 1.5,
      cell_size: 10,
      time_of_interest: 120,
      output: CbrnOutput.contours,
      comment: '',
    } as IControlParameters;
  }
  if (!source.scenario) {
    source.scenario = {
      // start_of_release:
      quantity: 0,
      release_rate: 0,
      duration: 600,
      initial_size: 15,
      windspeed: 2,
      winddirection: 270,
      pasquill_class: PasquillClass.D,
      roughness_length: 0.1,
      source_height: 2,
    } as IScenarioDefinition;
  }
  // if (source.scenario.quantity > 0 && source.scenario.release_rate > 0) {
  //   source.scenario.release_rate = 0;
  // }
  return [
    { id: 'source', type: 'section' },
    {
      id: 'control_parameters',
      label: '##### Control parameters',
      className: 'col s12',
      type: [
        {
          id: 'output',
          label: 'Output',
          type: 'select',
          className: 'col m6',
          options: [
            { id: 'template' , label: 'template' },
            { id: 'contours', label: 'contours' },
            { id: 'both', label: 'both' },
            { id: 'ensemble', label: 'ensemble' },
            { id: 'trajectories', label: 'trajectories' },
          ],
        },
        {
          id: 'time_of_interest',
          show: ['output=contours', 'output=both'],
          label: 'Time of interest [s]',
          type: 'number',
          className: 'col m6',
          value: 900,
        },
      ],
    },
    {
      id: 'scenario',
      label: '##### Scenario',
      className: 'col s12',
      type: [
        {
          id: 'id',
          label: 'Name',
          type: 'text',
          value: 'Leakage of (what) at (where)',
          className: 'col m12',
        },
        {
          id: 'start_of_release',
          label: 'Start of release',
          type: 'time',
          className: 'col m6',
          transform,
        },
        { type: 'md', 
          value: '###### Specify source', 
          className: 'col s12' },
        {
          id: 'type_of_release',
          show: '!control_parameters.output=template',
          type: 'select',
          label: 'Release type',
          options: [
            { id: 'instantaneous', label: 'instantaneous' },
            { id: 'continuous', label: '(semi) continuous' },
          ],
          className: 'col m6',
        },
        {
          id: 'initial_size',
          show: 'control_parameters.mode=advanced',
          label: 'Initial size [m]',
          type: 'number',
          className: 'col m6',
          min: 1,
          max: 25,
          required: true,
        },
        {
          id: 'quantity',
          show: 'type_of_release=instantaneous',
          label: 'Quantity [kg]',
          type: 'number',
          className: 'col m6',
          min: 1,
          max: 1000000,
          // required: source.extended?.useQuantity,
        },
        {
          id: 'release_rate',
          show: 'type_of_release=continuous',
          label: 'Release rate [kg/s]',
          type: 'number',
          className: 'col m6',
          min: 0,
          max: 1000,
          // required: !source.extended?.useQuantity,
        },
        {
          id: 'duration',
          show: ['type_of_release=continuous', 'control_parameters.mode=advanced'],
          label: 'Duration [s]',
          type: 'number',
          className: 'col m6',
          // required: !source.extended?.useQuantity,
        },
        {
          id: 'source_height',
          show: '!control_parameters.output=template',
          label: 'Source height [m]',
          type: 'number',
          className: 'col m6',
        },
        {
          id: 'chemical',
          show: '!control_parameters.output=template',
          label: 'Chemical',
          type: 'select',
          className: 'col m6',
          options: [
            { id: 'UnknownMedium', label: 'UnknownMedium' },
            { id: 'UnknownHigh', label: 'UnknownHigh' },
            { id: 'UnknownLow', label: 'UnknownLow' },
            { id: 'Aceetaldehyde', label: 'Aceetaldehyde' },
            { id: 'Aceton', label: 'Aceton' },
            { id: 'Acetoncyaanhydrine', label: 'Acetoncyaanhydrine' },
            { id: 'Acetonitril', label: 'Acetonitril' },
            { id: 'Acetylchloride', label: 'Acetylchloride' },
            { id: 'Acetyleen', label: 'Acetyleen' },
            { id: 'Acroleine', label: 'Acroleine' },
            { id: 'Acrylnitril', label: 'Acrylnitril' },
            { id: 'Acrylzuur', label: 'Acrylzuur' },
            { id: 'Allylalcohol', label: 'Allylalcohol' },
            { id: 'Allylamine', label: 'Allylamine' },
            { id: 'Allylbromide', label: 'Allylbromide' },
            { id: 'Allylchloride', label: 'Allylchloride' },
            { id: 'Allylglycidylether', label: 'Allylglycidylether' },
            { id: 'Aluminiumfosfide', label: 'Aluminiumfosfide' },
            { id: 'Ammoniak', label: 'Ammoniak' },
            { id: 'Amylmercaptanen', label: 'Amylmercaptanen' },
            { id: 'Aniline', label: 'Aniline' },
            { id: 'Arsine', label: 'Arsine' },
            { id: 'Azijnzuur', label: 'Azijnzuur' },
            { id: 'Azijnzuuranhydride', label: 'Azijnzuuranhydride' },
            { id: 'Aziridine', label: 'Aziridine' },
            { id: 'Benzeen', label: 'Benzeen' },
            { id: 'Benzine', label: 'Benzine' },
            { id: 'Benzylchloride', label: 'Benzylchloride' },
            { id: 'Boriumtribromide', label: 'Boriumtribromide' },
            { id: 'Boriumtrichloride', label: 'Boriumtrichloride' },
            { id: 'Boriumtrifluoride', label: 'Boriumtrifluoride' },
            { id: 'sec-Butylamine', label: 'sec-Butylamine' },
            { id: 'tert-Butylhydroperoxide', label: 'tert-Butylhydroperoxide' },
            { id: 'n-Butylisocyanaat', label: 'n-Butylisocyanaat' },
            { id: 'Calciumfosfide', label: 'Calciumfosfide' },
            { id: 'Carbonylfluoride', label: 'Carbonylfluoride' },
            { id: 'Carbonylsulfide', label: 'Carbonylsulfide' },
            { id: 'Chinon', label: 'Chinon' },
            { id: 'Chloor', label: 'Chloor' },
            { id: 'Chlooraceton', label: 'Chlooraceton' },
            { id: 'Chlooracetylchloride', label: 'Chlooracetylchloride' },
            { id: 'Chloorcyaan', label: 'Chloorcyaan' },
            { id: '1-Chloor-1,1-difluorethaan', label: '1-Chloor-1,1-difluorethaan' },
            { id: 'Chloordioxide', label: 'Chloordioxide' },
            { id: '2-Chloorethanal', label: '2-Chloorethanal' },
            { id: 'Crotonaldehyde', label: 'Crotonaldehyde' },
            { id: 'Cumeen', label: 'Cumeen' },
            { id: 'Cumeenhydroperoxide', label: 'Cumeenhydroperoxide' },
            { id: 'Cyaanwaterstof', label: 'Cyaanwaterstof' },
            { id: 'Cyclohexanon', label: 'Cyclohexanon' },
            { id: 'Cyclohexylamine', label: 'Cyclohexylamine' },
            { id: 'Cyclohexylisocyanaat', label: 'Cyclohexylisocyanaat' },
            { id: 'Cyclosarin', label: 'Cyclosarin' },
            { id: 'Diallylamine', label: 'Diallylamine' },
            { id: 'Diboraan', label: 'Diboraan' },
            { id: 'Dichlooracetylchloride', label: 'Dichlooracetylchloride' },
            { id: 'Dichloordifluormethaan', label: 'Dichloordifluormethaan' },
            { id: 'Dichloordimethylether', label: 'Dichloordimethylether' },
            { id: '1,1-Dichloorethaan', label: '1,1-Dichloorethaan' },
            { id: 'Diethylsulfide', label: 'Diethylsulfide' },
            { id: 'Difenyl', label: 'Difenyl' },
            { id: 'Difenyldichloorsilaan', label: 'Difenyldichloorsilaan' },
            { id: 'Difenylmethaan-4,4 - diisocyanaat', label: 'Difenylmethaan - 4, 4-diisocyanaat' },
            { id: 'Difenyloxide', label: 'Difenyloxide' },
            { id: '1,1-Difluorethyleen', label: '1,1-Difluorethyleen' },
            { id: 'Diisodecylftalaat', label: 'Diisodecylftalaat' },
            { id: 'Diketeen', label: 'Diketeen' },
            { id: 'Dimethylamine', label: 'Dimethylamine' },
            { id: 'Dimethyldichloorsilaan', label: 'Dimethyldichloorsilaan' },
            { id: 'Dimethyldisulfide', label: 'Dimethyldisulfide' },
            { id: 'Dimethylether', label: 'Dimethylether' },
            { id: 'Dimethylformamide', label: 'Dimethylformamide' },
            { id: '1,1-Dimethylhydrazine', label: '1,1-Dimethylhydrazine' },
            { id: 'Dimethylsulfaat', label: 'Dimethylsulfaat' },
            { id: 'Dimethylsulfide', label: 'Dimethylsulfide' },
            { id: '2,4-Dinitroaniline', label: '2,4-Dinitroaniline' },
            { id: '1,4-Dioxaan', label: '1,4-Dioxaan' },
            { id: 'Epichloorhydrine', label: 'Epichloorhydrine' },
            { id: 'Ethanol', label: 'Ethanol' },
            { id: 'Etheen', label: 'Etheen' },
            { id: 'Ether', label: 'Ether' },
            { id: 'Ethylacetaat', label: 'Ethylacetaat' },
            { id: 'Ethylacrylaat', label: 'Ethylacrylaat' },
            { id: 'Ethylamine', label: 'Ethylamine' },
            { id: 'Ethylbenzeen', label: 'Ethylbenzeen' },
            { id: 'Ethylbromide', label: 'Ethylbromide' },
            { id: 'Ethylbroomacetaat', label: 'Ethylbroomacetaat' },
            { id: 'Fenylisocyanaat', label: 'Fenylisocyanaat' },
            { id: 'Fluor', label: 'Fluor' },
            { id: 'Fluorwaterstof', label: 'Fluorwaterstof' },
            { id: 'Formaldehyde', label: 'Formaldehyde' },
            { id: 'Fosfine', label: 'Fosfine' },
            { id: 'Fosforoxychloride', label: 'Fosforoxychloride' },
            { id: 'Fosforpentasulfide', label: 'Fosforpentasulfide' },
            { id: 'Fosforpentoxide', label: 'Fosforpentoxide' },
            { id: 'Fosfortribromide', label: 'Fosfortribromide' },
            { id: 'Fosfortrichloride', label: 'Fosfortrichloride' },
            { id: 'Fosforzuur', label: 'Fosforzuur' },
            { id: 'Fosgeen', label: 'Fosgeen' },
            { id: 'Furaan', label: 'Furaan' },
            { id: 'Furfural', label: 'Furfural' },
            { id: 'Gasolie', label: 'Gasolie' },
            { id: 'Glutaaraldehyde', label: 'Glutaaraldehyde' },
            { id: 'Heptaan', label: 'Heptaan' },
            { id: 'Hexaan', label: 'Hexaan' },
            { id: 'Hexachloorbutadieen', label: 'Hexachloorbutadieen' },
            { id: 'Hexachloorcyclopentadieen', label: 'Hexachloorcyclopentadieen' },
            { id: 'Hexafluoraceton', label: 'Hexafluoraceton' },
            { id: 'Hexanol', label: 'Hexanol' },
            { id: 'Hydrazine', label: 'Hydrazine' },
            { id: 'IJzercarbonyl', label: 'IJzercarbonyl' },
            { id: 'Isobutaan', label: 'Isobutaan' },
            { id: 'Isobutanol', label: 'Isobutanol' },
            { id: 'Isobutylacetaat', label: 'Isobutylacetaat' },
            { id: 'Isobutylacrylaat', label: 'Isobutylacrylaat' },
            { id: 'Isobutylamine', label: 'Isobutylamine' },
            { id: 'Isobutyleen', label: 'Isobutyleen' },
            { id: 'Isobutylisocyanaat', label: 'Isobutylisocyanaat' },
            { id: 'Isobutylmethacrylaat', label: 'Isobutylmethacrylaat' },
            { id: 'Isobutyronitril', label: 'Isobutyronitril' },
            { id: 'Isoforon', label: 'Isoforon' },
            { id: 'Isopentaan', label: 'Isopentaan' },
            { id: 'Isopreen', label: 'Isopreen' },
            { id: '2-isocyanatoethylmethacrylaat', label: '2-isocyanatoethylmethacrylaat' },
            { id: 'Isopropylacetaat', label: 'Isopropylacetaat' },
            { id: 'Isopropylalcohol', label: 'Isopropylalcohol' },
            { id: 'Isopropylamine', label: 'Isopropylamine' },
            { id: 'Isopropylchloride', label: 'Isopropylchloride' },
            { id: 'Isopropylchloorformiaat', label: 'Isopropylchloorformiaat' },
            { id: 'Magnesiumfosfide', label: 'Magnesiumfosfide' },
            { id: 'Maleinezuuranhydride', label: 'Maleinezuuranhydride' },
            { id: 'Methacrylaldehyde', label: 'Methacrylaldehyde' },
            { id: 'Methacrylonitril', label: 'Methacrylonitril' },
            { id: 'Methanol', label: 'Methanol' },
            { id: 'Methylacetaat', label: 'Methylacetaat' },
            { id: 'Methylacetyleen/propadieen', label: 'Methylacetyleen/propadieen' },
            { id: 'Methylacrylaat', label: 'Methylacrylaat' },
            { id: 'Methylal', label: 'Methylal' },
            { id: 'Methylamine', label: 'Methylamine' },
            { id: 'Methylbromide', label: 'Methylbromide' },
            { id: 'Methylchloorformiaat', label: 'Methylchloorformiaat' },
            { id: 'Methylchloride', label: 'Methylchloride' },
            { id: 'Methyleenchloride', label: 'Methyleenchloride' },
            { id: 'N-Methylethylamine', label: 'N-Methylethylamine' },
            { id: 'Methylethylketon', label: 'Methylethylketon' },
            { id: 'Methylformiaat', label: 'Methylformiaat' },
            { id: 'Methylhydrazine', label: 'Methylhydrazine' },
            { id: 'Methylisobutylcarbinol', label: 'Methylisobutylcarbinol' },
            { id: 'Methylisocyanaat', label: 'Methylisocyanaat' },
            { id: 'Methyljodide', label: 'Methyljodide' },
            { id: 'Methylmercaptaan', label: 'Methylmercaptaan' },
            { id: 'Methylmethacrylaat', label: 'Methylmethacrylaat' },
            { id: 'Methylnonafluoro(iso)butylether', label: 'Methylnonafluoro(iso)butylether' },
            { id: 'Methylsilicaat', label: 'Methylsilicaat' },
            { id: 'a-Methylstyreen', label: 'a-Methylstyreen' },
            { id: 'Methyl-tert -butylether', label: 'Methyl-tert -butylether' },
            { id: 'Methyltrichloorsilaan', label: 'Methyltrichloorsilaan' },
            { id: 'Osmiumtetraoxide', label: 'Osmiumtetraoxide' },
            { id: 'Ozon', label: 'Ozon' },
            { id: 'Parathion', label: 'Parathion' },
            { id: 'n-Pentaan', label: 'n-Pentaan' },
            { id: 'Pentaboraan', label: 'Pentaboraan' },
            { id: 'Perazijnzuur', label: 'Perazijnzuur' },
            { id: 'Perchloorethyleen', label: 'Perchloorethyleen' },
            { id: 'Perchloormethylmercaptaan', label: 'Perchloormethylmercaptaan' },
            { id: 'Perfluorisobutyleen', label: 'Perfluorisobutyleen' },
            { id: 'Piperazine', label: 'Piperazine' },
            { id: 'Piperidine', label: 'Piperidine' },
            { id: 'Propaan', label: 'Propaan' },
            { id: 'n-Propanol', label: 'n-Propanol' },
            { id: 'Propeen', label: 'Propeen' },
            { id: 'Propyltrichloorsilaan', label: 'Propyltrichloorsilaan' },
            { id: 'Pyridine', label: 'Pyridine' },
            { id: 'Salpeterzuur (70%)', label: 'Salpeterzuur (70%)' },
            { id: 'Sarin', label: 'Sarin' },
            { id: 'Seleenhexafluoride', label: 'Seleenhexafluoride' },
            { id: 'Seleenwaterstof', label: 'Seleenwaterstof' },
            { id: 'Silaan', label: 'Silaan' },
            { id: 'Siliciumtetrachloride', label: 'Siliciumtetrachloride' },
            { id: 'Stibine', label: 'Stibine' },
            { id: 'Stikstofdioxide', label: 'Stikstofdioxide' },
            { id: 'Stikstofmonoxide', label: 'Stikstofmonoxide' },
            { id: 'Stikstoftrifluoride', label: 'Stikstoftrifluoride' },
            { id: 'Strontiumfosfide', label: 'Strontiumfosfide' },
            { id: 'Styreen', label: 'Styreen' },
            { id: 'Tolueen-2,6-diisocyanaat', label: 'Tolueen-2,6-diisocyanaat' },
            { id: 'Traangas', label: 'Traangas' },
            { id: '1,1,1-Trichloorethaan', label: '1,1,1-Trichloorethaan' },
            { id: 'Trichloorethyleen', label: 'Trichloorethyleen' },
            { id: 'Trichloorsilaan', label: 'Trichloorsilaan' },
            { id: 'Triethylaluminium', label: 'Triethylaluminium' },
            { id: 'Triethylamine', label: 'Triethylamine' },
            { id: 'Trifluorazijnzuur', label: 'Trifluorazijnzuur' },
            { id: 'Trifluorbroommethaan', label: 'Trifluorbroommethaan' },
            { id: 'Trimethoxysilaan', label: 'Trimethoxysilaan' },
            { id: 'Trimethylamine', label: 'Trimethylamine' },
            { id: '1,2,3-trimethylbenzeen', label: '1,2,3-trimethylbenzeen' },
            { id: '1,2,4-trimethylbenzeen', label: '1,2,4-trimethylbenzeen' },
            { id: '1,3,5-trimethylbenzeen', label: '1,3,5-trimethylbenzeen' },
            { id: 'Trimethylchloorsilaan', label: 'Trimethylchloorsilaan' },
            { id: 'Triuraniumoctaoxide', label: 'Triuraniumoctaoxide' },
            { id: 'Uraniumdioxide', label: 'Uraniumdioxide' },
            { id: 'Uraniumhexafluoride', label: 'Uraniumhexafluoride' },
            { id: 'Valeriaanaldehyde', label: 'Valeriaanaldehyde' },
            { id: 'Vinylacetaat', label: 'Vinylacetaat' },
            { id: 'Vinylbromide', label: 'Vinylbromide' },
            { id: 'Vinylchloride', label: 'Vinylchloride' },
            { id: 'Vinylethylether', label: 'Vinylethylether' },
            { id: 'Vinyltrichloorsilaan', label: 'Vinyltrichloorsilaan' },
            { id: 'Vinyltrimethoxisilaan', label: 'Vinyltrimethoxisilaan' },
            { id: 'VX', label: 'VX' },
            { id: 'Waterstof', label: 'Waterstof' },
            { id: 'Waterstofperoxide (90%)', label: 'Waterstofperoxide (90%)' },
            { id: 'Xylenen', label: 'Xylenen' },
            { id: 'Xylidine', label: 'Xylidine' },
            { id: 'Zinkfosfide', label: 'Zinkfosfide' },
            { id: 'Zwavelchloride', label: 'Zwavelchloride' },
            { id: 'Zwaveldichloride', label: 'Zwaveldichloride' },
            { id: 'Zwaveldioxide', label: 'Zwaveldioxide' },
            { id: 'Zwavelkoolstof', label: 'Zwavelkoolstof' },
            { id: 'Zwavelmosterd', label: 'Zwavelmosterd' },
            { id: 'Zwaveltetrafluoride', label: 'Zwaveltetrafluoride' },
            { id: 'Zwaveltrioxide', label: 'Zwaveltrioxide' },
            { id: 'Zwavelwaterstof', label: 'Zwavelwaterstof' },
            { id: 'Zwavelzuur', label: 'Zwavelzuur' },
          ],
        },
        {
          id: 'toxicity',
          show: 'chemical=unknown',
          label: 'Toxicity',
          type: 'select',
          value: 'medium',
          className: 'col m6',
          options: [
            { id: 'verylow', label: 'Very low' },
            { id: 'low' },
            { id: 'medium' },
            { id: 'high' },
            { id: 'veryhigh', label: 'Very high' },
          ],
        },
        { type: 'md', value: '###### Meteorology', className: 'col s12' },
        {
          id: 'use_meteo_service',
          type: 'checkbox',
          label: 'Wind direction and speed from external service',
          value: 'true',
          className: 'col m12',
        },
        {
          id: 'windspeed',
          show: 'use_meteo_service=false',
          label: 'Wind speed [m/s]',
          type: 'number',
          className: 'col s12 m6',
          required: true,
        },
        {
          id: 'winddirection',
          show: 'use_meteo_service=false',
          label: 'Wind direction [DGT]',
          type: 'number',
          className: 'col s12 m6',
          required: true,
        },
        {
          id: 'pasquill_class',
          show: '!control_parameters.output=template',
          label: 'Pasquill class',
          type: 'select',
          options: [
            { id: 'A', label: 'Very unstable' },
            { id: 'B', label: 'Unstable' },
            { id: 'C', label: 'Slightly Unstable' },
            { id: 'D', label: 'Neutral' },
            { id: 'E', label: 'Slightly stable' },
            { id: 'F', label: 'Stable' },
          ],
          required: true,
          className: 'col s12 m6',
        },
      ],
    },
    { id: 'settings', type: 'section' },
    {
      id: 'control_parameters',
      label: '##### Control parameters',
      className: 'col s12',
      type: [
        {
          id: 'mode',
          type: 'select',
          options: [
            { id: 'simple', label: 'Simple'},
            { id: 'advanced', label: 'Advanced'},
          ],
          value: 'simple',
        },
        {
          id: 'z',
          type: 'number',
          value: 1.5,
        },
        {
          id: 'comment',
          label: 'Comment',
          type: 'textarea',
        },
      ],
    },
  ] as Form;
};
